import torch
import torch.nn.functional as F
import joblib
from transformers import AutoTokenizer, DebertaV2ForSequenceClassification


def load_detector(model_path):
    tokenizer = AutoTokenizer.from_pretrained(model_path)
    model = DebertaV2ForSequenceClassification.from_pretrained(model_path)
    le = joblib.load(f"{model_path}/label_encoder.pkl")
    prototypes = joblib.load(f"{model_path}/prototypes.pkl")  # Generated by Step 4
    return model, tokenizer, le, prototypes


def predict(text, model, tokenizer, le, prototypes, threshold=95.0):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=256)

    with torch.no_grad():
        out = model(**inputs, output_hidden_states=True)
        logits = out.logits.float()

        # --- STEP 3 & 4 LOGIC ---
        # 1. Energy Score (Outlier Detection)
        energy = -torch.logsumexp(logits, dim=1).item()

        # 2. Prototypical Similarity (Family Attribution)
        # Use the [CLS] token from last layer
        query_emb = F.normalize(out.hidden_states[-1][:, 0, :], dim=-1)

        best_sim = -1
        best_model = None
        for model_name, proto in prototypes.items():
            sim = torch.dot(query_emb[0], proto.to(query_emb.device)).item()
            if sim > best_sim:
                best_sim = sim
                best_model = model_name

        # Decision Boundary
        # Based on "Human Texts Are Outliers", human/unseen text will have
        # high energy AND low similarity to known AI prototypes.
        if energy > threshold or best_sim < 0.75:
            return {"result": "Human / Unseen LLM", "energy": energy, "sim": best_sim}

        return {"result": best_model, "energy": energy, "sim": best_sim}


# Example usage:
# model, tokenizer, le, protos = load_detector("./results/run1/final_model")
# print(predict("Your sample text here", model, tokenizer, le, protos))
