[project]
name = "hound"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "datasets>=4.8.4",
    "joblib>=1.5.3",
    "numpy>=2.2.6",
    "python-dotenv>=1.2.2",
    "pytorch-metric-learning>=2.9.0",
    "scikit-learn>=1.7.2",
    "sentencepiece>=0.2.1",
    "tiktoken>=0.12.0",
    "torch>=2.11.0",
    "transformers>=5.5.4",
    "wandb>=0.26.0",
]
